name:                fromhtml
version:             0.1.0.4
github:              "MarekSuchanek/FromHTML"
license:             MIT
author:              "Marek Suchánek"
maintainer:          "marek.suchanek@fit.cvut.cz"
copyright:           "2018 Marek Suchánek"
category:            "Text"
synopsis:            "Simple adapter for transformation of HTML to other formats"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MarekSuchanek/FromHTML#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- process
- text

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings

executables:
  fromhtml:
    main: Main.hs
    source-dirs: app
    dependencies:
    - fromhtml
